# Generated by Django 2.2.16 on 2020-10-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20201018_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergeneral',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
