# Generated by Django 2.2.16 on 2020-10-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20201018_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergeneral',
            old_name='id',
            new_name='cedula',
        ),
    ]
